language: csharp
solution: Unosquare.Tubular.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
mono: none
dotnet: 2.2.101
dist: xenial
sudo: false
install:
  - dotnet restore
script:
  - dotnet test ./test/Unosquare.Tubular.Tests/Unosquare.Tubular.Tests.csproj
