version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#general'
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:  
       secure: tMQ8tkErQ8zJr+uwZd8xXFfuYCTbHaZoA3M0pJuShvrcQJswmMLgaKo7Pn+YK5eL
before_build:
- appveyor-retry dotnet restore -v Minimal
- mkdir tools
- nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools
build_script:
- dotnet build */**/project.json -c %CONFIGURATION%
test_script:
- tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"%ProgramFiles%\dotnet\dotnet.exe" -targetargs:"test test\Unosquare.Tubular.Tests -c %CONFIGURATION%" -output:coverage.xml -filter:"+[Unosquare.Tubular*]* -[Unosquare.Tubular.Tests*]*" -register:userdotnet
- tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%
cache:
- '%USERPROFILE%\.nuget\packages'
